# Generated by Django 4.2.23 on 2025-07-16 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='name',
            field=models.CharField(default='페스티벌', max_length=50),
            preserve_default=False,
        ),
    ]
