version: "3.9"

services:
  web:
    image: ${ DOCKERHUB_USERNAME }/ticket-backend:dev-latest
    container_name: django-backend
    command: gunicorn ticket_backend.wsgi:application --bind 0.0.0.0:8000
    ports:
      - "8000:8000"
    # volumes:
    #   - .:/app
    env_file:
      - .env
    depends_on:
      - db

  db:
    image: mysql:8.0
    container_name: mysql-db
    restart: always
    environment:
      MYSQL_DATABASE: ${ MYSQL_DATABASE }
      MYSQL_USER: ${ MYSQL_USER }
      MYSQL_PASSWORD: ${ MYSQL_PASSWORD }
      MYSQL_ROOT_PASSWORD: ${ MYSQL_ROOT_PASSWORD }

    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
