global:
  scrape_interval: 10s

scrape_configs:
  - job_name: 'node-exporter'
    static_configs:
      - targets: ['node-exporter:9100']

  - job_name: 'prometheus'
    static_configs:
      - targets: ['prometheus:9090']

  - job_name: 'cadvisor'
    static_configs:
      - targets: ['cadvisor:8080']

  - job_name: 'django_app'
    metrics_path: /metrics
    static_configs:
      - targets: ['django-backend:8000']

alerting:
  alertmanagers:
    - static_configs:
        - targets:
            - 'alertmanager:9093'  # Alertmanager가 실행 중인 주소

rule_files:
  - 'alert_rules.yml'  # 알림 룰이 담긴 파일

  
