global:
  scrape_interval: 10s

scrape_configs:
  - job_name: 'cadvisor'
    static_configs:
      - targets: ['cadvisor:8080']

  - job_name: 'otel-collector'
    static_configs:
      - targets: ['otel-collector:8888']
