# Generated by Django 4.2.23 on 2025-07-13 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchase',
            name='email',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='purchase',
            name='phone_number',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='purchase',
            name='purchaser',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
