name: Django CD

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/tecker-backend:latest

      # 아래 단계는 실제 배포 환경에 맞게 추가/수정하세요.
      # 예: 서버에 SSH 접속 후 도커 pull & 재시작, AWS ECS/ECR 배포 등
      # - name: Deploy to server
      #   run: |
      #     ssh ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_IP }} 'docker pull ... && docker-compose up -d' 