name: Django CI

on:
  push:
    branches: [main, develop]
  pull_request:
    branches: [main, develop]

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:8.0
        env:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: ticketing
          MYSQL_USER: ticketuser
          MYSQL_PASSWORD: ticketpass
        ports:
          - 3306:3306
        options: >-
          --health-cmd="mysqladmin ping --silent" --health-interval=10s --health-timeout=5s --health-retries=3

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Wait for MySQL
        run: |
          until mysqladmin ping -h "127.0.0.1" -u"ticketuser" -p"ticketpass" --silent; do
            sleep 2
          done

      - name: Run migrations
        env:
          DJANGO_SECRET_KEY: test-secret-key
          DEBUG: "False"
          MYSQL_DATABASE: ticketing
          MYSQL_USER: ticketuser
          MYSQL_PASSWORD: ticketpass
          MYSQL_HOST: 127.0.0.1
          MYSQL_PORT: 3306
        run: |
          python manage.py migrate

      - name: Run tests
        env:
          DJANGO_SECRET_KEY: test-secret-key
          DEBUG: "False"
          MYSQL_DATABASE: ticketing
          MYSQL_USER: ticketuser
          MYSQL_PASSWORD: ticketpass
          MYSQL_HOST: 127.0.0.1
          MYSQL_PORT: 3306
        run: |
          python manage.py test
