name: Django CI

on:
  push:
    branches:
      - main
      - develop
  pull_request:
    branches:
      - main
      - develop

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      DJANGO_SECRET_KEY: test-secret-key
      DEBUG: "False"
      MYSQL_DATABASE: ticketing
      MYSQL_USER: ticketuser
      MYSQL_PASSWORD: ticketpass
      MYSQL_HOST: 127.0.0.1
      MYSQL_PORT: 3306

    services:
      mysql:
        image: mysql:8.0
        env:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: ticketing
          MYSQL_USER: ticketuser
          MYSQL_PASSWORD: ticketpass
        ports:
          - 3306:3306
        options: >-
          —health-cmd="mysqladmin ping —silent"
          —health-interval=10s
          —health-timeout=5s
          —health-retries=5

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          python -m pip install —upgrade pip
          pip install -r requirements.txt

      - name: Wait for MySQL to be ready
        run: |
          timeout 60 bash -c \
            'until mysqladmin ping -h "$MYSQL_HOST" -u"$MYSQL_USER" -p"$MYSQL_PASSWORD" —silent; do sleep 2; done'

      - name: Run Django migrations
        run: python manage.py migrate

      - name: Run tests
        run: python manage.py test
